import NavBar from "@/components/NavBar/NavBar";
import { ReduxProvider } from "@/redux/provider";
import { Inter } from "next/font/google";
import "./globals.css";
import SetupDatePicker from "@/mui-core/SetupDatePicker/SetupDatePicker";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body>
          <SetupDatePicker>{children}</SetupDatePicker>
        </body>
      </ReduxProvider>
    </html>
  );
}
